"""add user.email_verified

Revision ID: f609210432b5
Revises: c4b5d92a3172
Create Date: 2026-06-11 13:56:27.551791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f609210432b5'
down_revision = 'c4b5d92a3172'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=True))

    # Mevcut kullanıcıları mağdur etme: bu kolon eklenmeden önce kayıt olanlar
    # "doğrulanmış" sayılır. Yeni kayıtlar uygulama default'u ile False başlar.
    user_table = sa.table('user', sa.column('email_verified', sa.Boolean))
    op.execute(user_table.update().values(email_verified=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email_verified')

    # ### end Alembic commands ###
